name: JSONAPI
main: com.alecgorge.minecraft.jsonapi.JSONAPI
version: 1.0.0
description: Control your server and fetch information from your server.
website: http://mcjsonapi.com/
author: Dirk Sarodnick
softdepend: [ProtocolLib]
commands:
  jsonapi-list:
    description: Lists all the methods and namespaces currently loaded for JSONAPI
    usage: /<command>
  jsonapi:
    usage: '/<command> [status|list|reload|reloadgroups|subscribe <source name> <url>|users [list|<username> password|add <username> <password>]]'
    description: '/jsonapi [status|list|reload|reloadgroups|subscribe <source name> <url>|users [list|<username> password|add <username> <password>]]'
permissions:
  jsonapi.command:
    description: The ability to use the /jsonapi and /adminium commands
    default: op